version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/pino"
    versions:
    - 6.3.5
    - 6.3.6
    - 6.3.7
  - dependency-name: concurrently
    versions:
    - 5.3.0
    - 6.0.0
    - 6.0.1
  - dependency-name: pino
    versions:
    - 6.11.0
    - 6.11.1
    - 6.11.2
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: find-my-way
    versions:
    - 3.0.5
    - 4.0.0
  - dependency-name: joi
    versions:
    - 17.3.0
